version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=root_password
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads  # Keeps uploaded images safe

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: goviya_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Keeps database data safe even if you restart

volumes:
  db_data: